### TODO:
1. Load multiple dataset for different buildings.
2. Get the climate info for the state.
3. preprocess the data.
4. Create a linear regression model.
5. Prepare some tests for the model.

In [184]:
import polars.selectors as cs
import polars as pl
import pyarrow
import pandas as pd
import numpy as np

In [185]:
from pathlib import Path
folder= Path().resolve().parent /'input'
meta_data_folder=Path().resolve().parent / 'metadata'

### 1. Load multiple dataset for different buildings.

In [186]:
# read the original data for three individual buildings
data=pl.scan_parquet(folder / '*')

In [187]:
# extract the buildings Ids
bldgs=data.select(pl.col('bldg_id').unique()).collect().to_series().to_list()

### 2. Get the climate info for the state.

In [188]:
pl.scan_parquet(meta_data_folder/'MetaData.parquet').collect().row(1, named=True)

{'bldg_id': 10,
 'completed_status': 'Success',
 'upgrade': 28,
 'in.upgrade_name': 'HVAC Demand Flexibility - Pre-peak Load Shifting, 2F Offset, 1hr Pre-peak Duration',
 'weight': 253.90367272727272,
 'applicability': True,
 'in.sqft..ft2': 1228.0,
 'in.representative_income': 32414.0,
 'in.county_name': 'Miami-Dade County',
 'in.ahs_region': 'CBSA Miami-Fort Lauderdale-West Palm Beach, FL',
 'in.aiannh_area': 'No',
 'in.area_median_income': '30-60%',
 'in.ashrae_iecc_climate_zone_2004': '1A',
 'in.ashrae_iecc_climate_zone_2004_sub_cz_split': '1A - FL',
 'in.bathroom_spot_vent_hour': 'Hour2',
 'in.battery': 'None',
 'in.bedrooms': '3',
 'in.building_america_climate_zone': 'Hot-Humid',
 'in.cec_climate_zone': 'None',
 'in.ceiling_fan': 'Standard Efficiency',
 'in.census_division': 'South Atlantic',
 'in.census_division_recs': 'South Atlantic',
 'in.census_region': 'South',
 'in.city': 'FL, Miami',
 'in.clothes_dryer': 'Electric',
 'in.clothes_dryer_usage_level': '100% Usage',
 'in.clothes_washer': 'EnergyStar',
 'in.clothes_washer_presence': 'Yes',
 'in.clothes_washer_usage_level': '100% Usage',
 'in.cooking_range': 'Electric Resistance',
 'in.cooking_range_usage_level': '100% Usage',
 'in.cooling_unavailable_days': '1 day',
 'in.cooling_setpoint': '75F',
 'in.cooling_setpoint_has_offset': 'No',
 'in.cooling_setpoint_offset_magnitude': '0F',
 'in.cooling_setpoint_offset_period': 'None',
 'in.corridor': 'Not Applicable',
 'in.county': 'G1200860',
 'in.county_and_puma': 'G1200860, G12008615',
 'in.county_metro_status': 'Metropolitan',
 'in.custom_state': 'Others',
 'in.dehumidifier': 'None',
 'in.dishwasher': 'None',
 'in.dishwasher_usage_level': '100% Usage',
 'in.door_area': '20 ft^2',
 'in.doors': 'Fiberglass',
 'in.duct_leakage_and_insulation': '0% Leakage to Outside, Uninsulated',
 'in.duct_location': 'Living Space',
 'in.eaves': '2 ft',
 'in.electric_panel_service_rating..a': 200.0,
 'in.electric_panel_service_rating_bin..a': '200',
 'in.electric_vehicle_battery': 'Compact, Battery Electric Vehicle, 300 mile range',
 'in.electric_vehicle_charge_at_home': '80-99%',
 'in.electric_vehicle_charger': 'None',
 'in.electric_vehicle_miles_traveled': '9000',
 'in.electric_vehicle_outlet_access': 'Yes',
 'in.electric_vehicle_ownership': 'No',
 'in.energystar_climate_zone_2023': 'Southern',
 'in.federal_poverty_level': '100-150%',
 'in.generation_and_emissions_assessment_region': 'FRCC',
 'in.geometry_attic_type': 'None',
 'in.geometry_building_horizontal_location_mf': 'None',
 'in.geometry_building_horizontal_location_sfa': 'None',
 'in.geometry_building_level_mf': 'None',
 'in.geometry_building_number_units_mf': 'None',
 'in.geometry_building_number_units_sfa': 'None',
 'in.geometry_building_type_acs': 'Mobile Home',
 'in.geometry_building_type_height': 'Mobile Home',
 'in.geometry_building_type_recs': 'Mobile Home',
 'in.geometry_floor_area': '1000-1499',
 'in.geometry_floor_area_bin': '0-1499',
 'in.geometry_foundation_type': 'Ambient',
 'in.geometry_garage': 'None',
 'in.geometry_space_combination': 'Mobile Home, Ambient, No Attic, No Garage',
 'in.geometry_stories': '1',
 'in.geometry_stories_low_rise': '1',
 'in.geometry_story_bin': '<8',
 'in.geometry_wall_exterior_finish': 'Wood, Medium/Dark',
 'in.geometry_wall_type': 'Wood Frame',
 'in.ground_thermal_conductivity': '1.1',
 'in.has_pv': 'No',
 'in.heating_fuel': 'Electricity',
 'in.heating_unavailable_days': '1 week',
 'in.heating_setpoint': '78F',
 'in.heating_setpoint_has_offset': 'No',
 'in.heating_setpoint_offset_magnitude': '0F',
 'in.heating_setpoint_offset_period': 'None',
 'in.holiday_lighting': 'No Exterior Use',
 'in.hot_water_distribution': 'Uninsulated',
 'in.hot_water_fixtures': '90% Usage',
 'in.household_has_tribal_persons': 'No',
 'in.hvac_cooling_autosizing_factor': 'None',
 'in.hvac_cooling_efficiency': 'Ducted Heat Pump',
 'in.hvac_cooling_partial_space_conditioning': '100% Conditioned',
 'in.hvac_cooling_type': 'Ducted Heat Pump',
 'in.hvac_has_ducts': 'Yes',
 'in.hvac_has_shared_system': 'None',
 'in.hvac_has_zonal_electric_heating': 'No',
 'in.hvac_heating_autosizing_factor': 'None',
 'in.hvac_heating_efficiency': 'ASHP, SEER 15, 8.5 HSPF',
 'in.hvac_heating_type': 'Ducted Heat Pump',
 'in.hvac_heating_type_and_fuel': 'Electricity ASHP',
 'in.hvac_secondary_heating_efficiency': 'None',
 'in.hvac_secondary_heating_fuel': 'None',
 'in.hvac_secondary_heating_partial_space_conditioning': '0%',
 'in.hvac_secondary_heating_type': 'None',
 'in.hvac_shared_efficiencies': 'None',
 'in.hvac_system_is_faulted': 'No',
 'in.hvac_system_is_scaled': 'No',
 'in.hvac_system_single_speed_ac_airflow': 'None',
 'in.hvac_system_single_speed_ac_charge': 'None',
 'in.hvac_system_single_speed_ashp_airflow': 'None',
 'in.hvac_system_single_speed_ashp_charge': 'None',
 'in.income': '30000-34999',
 'in.income_recs_2015': '20000-39999',
 'in.income_recs_2020': '20000-39999',
 'in.infiltration': '50 ACH50',
 'in.insulation_ceiling': 'None',
 'in.insulation_floor': 'Uninsulated',
 'in.insulation_foundation_wall': 'None',
 'in.insulation_rim_joist': 'None',
 'in.insulation_roof': 'Finished, R-30',
 'in.insulation_slab': 'None',
 'in.insulation_wall': 'Wood Stud, Uninsulated',
 'in.interior_shading': 'Summer = 0.7, Winter = 0.85',
 'in.iso_rto_region': 'None',
 'in.lighting': '100% LED',
 'in.lighting_interior_use': '100% Usage',
 'in.lighting_other_use': '100% Usage',
 'in.location_region': 'CR09',
 'in.mechanical_ventilation': 'None',
 'in.metropolitan_and_micropolitan_statistical_area': 'Miami-Fort Lauderdale-West Palm Beach, FL MSA',
 'in.misc_extra_refrigerator': 'None',
 'in.misc_freezer': 'None',
 'in.misc_gas_fireplace': 'Gas Fireplace',
 'in.misc_gas_grill': 'None',
 'in.misc_gas_lighting': 'None',
 'in.misc_hot_tub_spa': 'None',
 'in.misc_pool': 'None',
 'in.misc_pool_heater': 'None',
 'in.misc_pool_pump': 'None',
 'in.misc_well_pump': 'Typical Efficiency',
 'in.natural_ventilation': 'Cooling Season, 7 days/wk',
 'in.neighbors': 'Left/Right at 15ft',
 'in.occupants': '4',
 'in.orientation': 'East',
 'in.overhangs': 'None',
 'in.plug_load_diversity': '100%',
 'in.plug_loads': '110%',
 'in.puma': 'G12008615',
 'in.puma_metro_status': 'In metro area, principal city',
 'in.pv_orientation': 'None',
 'in.pv_system_size': 'None',
 'in.radiant_barrier': 'No',
 'in.range_spot_vent_hour': 'Hour10',
 'in.reeds_balancing_area': '102',
 'in.refrigerator': 'EF 17.6',
 'in.refrigerator_usage_level': '100% Usage',
 'in.roof_material': 'Asphalt Shingles, Medium',
 'in.state': 'FL',
 'in.state_metro_median_income': '30-60%',
 'in.tenure': 'Owner',
 'in.usage_level': 'Medium',
 'in.vacancy_status': 'Occupied',
 'in.vintage': '1940s',
 'in.vintage_acs': '1940-59',
 'in.water_heater_efficiency': 'Electric Standard',
 'in.water_heater_fuel': 'Electricity',
 'in.water_heater_in_unit': 'Yes',
 'in.water_heater_location': 'Living Space',
 'in.window_areas': 'F9 B9 L9 R9',
 'in.windows': 'Single, Clear, Non-metal',
 'in.air_leakage_to_outside_ach50': 50.0,
 'in.units_represented': 1,
 'in.simulation_control_run_period_begin_day_of_month': 1,
 'in.simulation_control_run_period_begin_month': 1,
 'in.simulation_control_run_period_calendar_year': 2018,
 'in.simulation_control_run_period_end_day_of_month': 31,
 'in.simulation_control_run_period_end_month': 12,
 'in.simulation_control_timestep': 15,
 'in.utility_bill_electricity_fixed_charges': '13.8',
 'in.utility_bill_electricity_marginal_rates': '0.139605448',
 'in.utility_bill_fuel_oil_fixed_charges': '0',
 'in.utility_bill_fuel_oil_marginal_rates': '3.526538462',
 'in.utility_bill_natural_gas_fixed_charges': '10',
 'in.utility_bill_natural_gas_marginal_rates': '1.863660544',
 'in.utility_bill_propane_fixed_charges': '0',
 'in.utility_bill_propane_marginal_rates': '4.751615385',
 'in.weather_file_city': 'Miami',
 'in.weather_file_latitude': 25.82,
 'in.weather_file_longitude': -80.3,
 'in.heating_unavailable_period': 'Dec 10 - Dec 16',
 'in.cooling_unavailable_period': 'Sep 23 - Sep 23',
 'out.params.door_area..ft2': 20.0,
 'out.params.duct_unconditioned_surface_area..ft2': 0.0,
 'out.params.floor_area_attic..ft2': 0.0,
 'out.params.floor_area_attic_insulation_increase..ft2_delta_r_value': 0.0,
 'out.params.floor_area_conditioned_infiltration_reduction..ft2_delta_ach50': 0.0,
 'out.params.floor_area_foundation..ft2': 0.0,
 'out.params.floor_area_lighting..ft2': 1228.0,
 'out.params.flow_rate_mechanical_ventilation..cfm': 0.0,
 'out.params.rim_joist_area_above_grade_exterior..ft2': 0.0,
 'out.params.roof_area..ft2': 1228.0,
 'out.params.size_cooling_system_primary..kbtu_per_hr': 45.06,
 'out.params.size_heat_pump_backup_primary..kbtu_per_hr': 20.38,
 'out.params.size_heating_system_primary..kbtu_per_hr': 45.06,
 'out.params.size_heating_system_secondary..kbtu_per_hr': 0.0,
 'out.params.size_water_heater..gal': 50.0,
 'out.params.slab_perimeter_exposed_conditioned..ft': 0.0,
 'out.params.wall_area_above_grade_conditioned..ft2': 1170.2,
 'out.params.wall_area_above_grade_exterior..ft2': 1170.2,
 'out.params.wall_area_below_grade..ft2': 0.0,
 'out.params.window_area..ft2': 105.4,
 'out.params.hvac_geothermal_loop_borehole_trench_count': 0.0,
 'out.params.hvac_geothermal_loop_borehole_trench_length..ft': 0.0,
 'out.electricity.ceiling_fan.energy_consumption..kwh': 163.24058610140003,
 'out.electricity.clothes_dryer.energy_consumption..kwh': 580.8668611364,
 'out.electricity.clothes_washer.energy_consumption..kwh': 33.9962441432,
 'out.electricity.cooling_fans_pumps.energy_consumption..kwh': 1234.1222766122,
 'out.electricity.cooling.energy_consumption..kwh': 5135.1912920444,
 'out.electricity.dishwasher.energy_consumption..kwh': 0.0,
 'out.electricity.ev_charging.energy_consumption..kwh': 0.0,
 'out.electricity.freezer.energy_consumption..kwh': 0.0,
 'out.electricity.heating_fans_pumps.energy_consumption..kwh': 45.426015881,
 'out.electricity.heating_hp_bkup.energy_consumption..kwh': 0.0,
 'out.electricity.heating_hp_bkup_fa.energy_consumption..kwh': 0.0,
 'out.electricity.heating.energy_consumption..kwh': 457.4839405822,
 'out.electricity.permanent_spa_heat.energy_consumption..kwh': 0.0,
 'out.electricity.permanent_spa_pump.energy_consumption..kwh': 0.0,
 'out.electricity.hot_water.energy_consumption..kwh': 1862.7597221912001,
 'out.electricity.hot_water_solar_th.energy_consumption..kwh': 0.0,
 'out.electricity.lighting_exterior.energy_consumption..kwh': 26.9625384584,
 'out.electricity.lighting_garage.energy_consumption..kwh': 0.0,
 'out.electricity.lighting_interior.energy_consumption..kwh': 376.88939627720004,
 'out.electricity.mech_vent.energy_consumption..kwh': 21.980330265,
 'out.electricity.plug_loads.energy_consumption..kwh': 1974.7128710076001,
 'out.electricity.pool_heater.energy_consumption..kwh': 0.0,
 'out.electricity.pool_pump.energy_consumption..kwh': 0.0,
 'out.electricity.pv.energy_consumption..kwh': 0.0,
 'out.electricity.range_oven.energy_consumption..kwh': 533.0962766938,
 'out.electricity.refrigerator.energy_consumption..kwh': 434.9174681768,
 'out.electricity.television.energy_consumption..kwh': 963.9107498878001,
 'out.electricity.well_pump.energy_consumption..kwh': 436.675894598,
 'out.fuel_oil.heating_hp_bkup.energy_consumption..kwh': 0.0,
 'out.fuel_oil.heating.energy_consumption..kwh': 0.0,
 'out.fuel_oil.hot_water.energy_consumption..kwh': 0.0,
 'out.natural_gas.clothes_dryer.energy_consumption..kwh': 0.0,
 'out.natural_gas.fireplace.energy_consumption..kwh': 1949.5087589704,
 'out.natural_gas.grill.energy_consumption..kwh': 0.0,
 'out.natural_gas.heating_hp_bkup.energy_consumption..kwh': 0.0,
 'out.natural_gas.heating.energy_consumption..kwh': 0.0,
 'out.natural_gas.permanent_spa_heat.energy_consumption..kwh': 0.0,
 'out.natural_gas.hot_water.energy_consumption..kwh': 0.0,
 'out.natural_gas.lighting.energy_consumption..kwh': 0.0,
 'out.natural_gas.pool_heater.energy_consumption..kwh': 0.0,
 'out.natural_gas.range_oven.energy_consumption..kwh': 0.0,
 'out.propane.clothes_dryer.energy_consumption..kwh': 0.0,
 'out.propane.heating_hp_bkup.energy_consumption..kwh': 0.0,
 'out.propane.heating.energy_consumption..kwh': 0.0,
 'out.propane.hot_water.energy_consumption..kwh': 0.0,
 'out.propane.range_oven.energy_consumption..kwh': 0.0,
 'out.site_energy.net.energy_consumption..kwh': 16231.155080886601,
 'out.site_energy.total.energy_consumption..kwh': 16231.155080886601,
 'out.electricity.net.energy_consumption..kwh': 14281.646321916201,
 'out.electricity.total.energy_consumption..kwh': 14281.646321916201,
 'out.fuel_oil.total.energy_consumption..kwh': 0.0,
 'out.natural_gas.total.energy_consumption..kwh': 1949.5087589704,
 'out.propane.total.energy_consumption..kwh': 0.0,
 'out.hot_water.clothes_washer..gal': 443.8,
 'out.hot_water.dishwasher..gal': 0.0,
 'out.hot_water.distribution_waste..gal': 3208.6,
 'out.hot_water.fixtures..gal': 11812.0,
 'out.capacity.cooling..btu_per_hr': 45057.0,
 'out.capacity.heat_pump_backup..btu_per_hr': 20380.0,
 'out.capacity.heating..btu_per_hr': 45057.0,
 'out.load.cooling.energy_delivered..kbtu': 53602.0,
 'out.load.heating.energy_delivered..kbtu': 4921.0,
 'out.load.hot_water.energy_delivered..kbtu': 5414.0,
 'out.load.hot_water.energy_solar_thermal..kbtu': 0.0,
 'out.load.hot_water.energy_tank_losses..kbtu': 939.0,
 'out.load.cooling.peak..kbtu_per_hr': 33.062,
 'out.load.heating.peak..kbtu_per_hr': 20.342,
 'out.qoi.electricity.maximum_daily_peak_summer..kw': 8.948500000000001,
 'out.qoi.electricity.maximum_daily_peak_winter..kw': 9.6811,
 'out.unmet_hours.cooling..hr': 58.0,
 'out.unmet_hours.ev_driving..hr': 0.0,
 'out.unmet_hours.heating..hr': 0.0,
 'out.emissions.electricity.lrmer_mid_case_25..co2e_kg': 3838.0037998995003,
 'out.emissions.total.lrmer_mid_case_25..co2e_kg': 4282.4336040255,
 'out.emissions.electricity.lrmer_mid_case_15..co2e_kg': 4148.374379072,
 'out.emissions.total.lrmer_mid_case_15..co2e_kg': 4592.804183198,
 'out.emissions.electricity.lrmer_high_re_cost_25..co2e_kg': 5201.8970894814,
 'out.emissions.total.lrmer_high_re_cost_25..co2e_kg': 5646.3268936074,
 'out.emissions.electricity.lrmer_high_re_cost_15..co2e_kg': 5668.0993273674,
 'out.emissions.total.lrmer_high_re_cost_15..co2e_kg': 6112.5291314934,
 'out.emissions.electricity.lrmer_low_re_cost_25..co2e_kg': 3867.9862555565005,
 'out.emissions.total.lrmer_low_re_cost_25..co2e_kg': 4312.4160596825,
 'out.emissions.electricity.lrmer_low_re_cost_15..co2e_kg': 4492.283578082301,
 'out.emissions.total.lrmer_low_re_cost_15..co2e_kg': 4936.713382208301,
 'out.emissions.electricity.lrmer_low_re_cost_high_ng_price_25..co2e_kg': 3224.1391018837003,
 'out.emissions.total.lrmer_low_re_cost_high_ng_price_25..co2e_kg': 3668.5689060097,
 'out.emissions.electricity.lrmer_low_re_cost_high_ng_price_15..co2e_kg': 3804.1385935553003,
 'out.emissions.total.lrmer_low_re_cost_high_ng_price_15..co2e_kg': 4248.568397681301,
 'out.emissions.electricity.lrmer_high_re_cost_low_ng_price_25..co2e_kg': 4832.0696224493,
 'out.emissions.total.lrmer_high_re_cost_low_ng_price_25..co2e_kg': 5276.4994265753,
 'out.emissions.electricity.lrmer_high_re_cost_low_ng_price_15..co2e_kg': 5242.3393851906,
 'out.emissions.total.lrmer_high_re_cost_low_ng_price_15..co2e_kg': 5686.7691893166,
 'out.emissions.electricity.aer_high_re_cost_avg..co2e_kg': 4817.654456930701,
 'out.emissions.total.aer_high_re_cost_avg..co2e_kg': 5262.084261056701,
 'out.emissions.electricity.aer_high_re_cost_low_ng_price_avg..co2e_kg': 4980.7889528012,
 'out.emissions.total.aer_high_re_cost_low_ng_price_avg..co2e_kg': 5425.2187569272,
 'out.emissions.electricity.aer_low_re_cost_avg..co2e_kg': 3892.9429077539,
 'out.emissions.total.aer_low_re_cost_avg..co2e_kg': 4337.3727118799,
 'out.emissions.electricity.aer_low_re_cost_high_ng_price_avg..co2e_kg': 3286.4082624373,
 'out.emissions.total.aer_low_re_cost_high_ng_price_avg..co2e_kg': 3730.8380665633,
 'out.emissions.electricity.aer_mid_case_avg..co2e_kg': 4295.8916896434,
 'out.emissions.total.aer_mid_case_avg..co2e_kg': 4740.3214937694,
 'out.utility_bills.electricity_bill..usd': 2159.41,
 'out.utility_bills.fuel_oil_bill..usd': 0.0,
 'out.utility_bills.natural_gas_bill..usd': 243.97,
 'out.utility_bills.propane_bill..usd': 0.0,
 'out.utility_bills.total_bill..usd': 2403.38,
 'out.params.panel_load_total_load.2023_nec_existing_dwelling_load_based..w': 23647.8,
 'out.params.panel_load_occupied_capacity.2023_nec_existing_dwelling_load_based..a': 98.5,
 'out.params.panel_load_headroom_capacity.2023_nec_existing_dwelling_load_based..a': 101.5,
 'out.params.panel_load_clothes_dryer..w': 5760.0,
 'out.params.panel_load_cooling..w': 7891.5,
 'out.params.panel_load_dishwasher..w': 0.0,
 'out.params.panel_load_ev_charging..w': 0.0,
 'out.params.panel_load_heating..w': 13769.3,
 'out.params.panel_load_hot_water..w': 5500.1,
 'out.params.panel_load_mech_vent..w': 60.0,
 'out.params.panel_load_other..w': 9284.0,
 'out.params.panel_load_permanent_spa_heat..w': 0.0,
 'out.params.panel_load_permanent_spa_pump..w': 0.0,
 'out.params.panel_load_pool_heater..w': 0.0,
 'out.params.panel_load_pool_pump..w': 0.0,
 'out.params.panel_load_range_oven..w': 12000.0,
 'out.params.panel_load_well_pump..w': 746.0,
 'in.electric_panel_breaker_space_total_count': 20.0,
 'out.params.panel_breaker_space_occupied_count': 20.0,
 'out.params.panel_breaker_space_headroom_count': 0.0,
 'out.params.panel_breaker_space_clothes_dryer_count': 2.0,
 'out.params.panel_breaker_space_cooling_count': 0.0,
 'out.params.panel_breaker_space_dishwasher_count': 0.0,
 'out.params.panel_breaker_space_ev_charging_count': 0.0,
 'out.params.panel_breaker_space_heating_count': 4.0,
 'out.params.panel_breaker_space_hot_water_count': 2.0,
 'out.params.panel_breaker_space_mech_vent_count': 2.0,
 'out.params.panel_breaker_space_other_count': 6.0,
 'out.params.panel_breaker_space_permanent_spa_heat_count': 0.0,
 'out.params.panel_breaker_space_permanent_spa_pump_count': 0.0,
 'out.params.panel_breaker_space_pool_heater_count': 0.0,
 'out.params.panel_breaker_space_pool_pump_count': 0.0,
 'out.params.panel_breaker_space_range_oven_count': 2.0,
 'out.params.panel_breaker_space_well_pump_count': 2.0,
 'out.params.panel_load_total_load_savings.2023_nec_existing_dwelling_load_based..w': 0.0,
 'out.params.panel_load_occupied_capacity_savings.2023_nec_existing_dwelling_load_based..a': 0.0,
 'out.params.panel_breaker_space_occupied_savings_count': 0.0,
 'out.params.panel_constraint_capacity.2023_nec_existing_dwelling_load_based': False,
 'out.params.panel_constraint_breaker_space': False,
 'out.params.panel_constraint_overall.2023_nec_existing_dwelling_load_based': 'No Constraint',
 'out.energy_burden..percentage': 7.4146356512618015,
 'out.electricity.ceiling_fan.energy_savings..kwh': 0.0,
 'out.electricity.clothes_dryer.energy_savings..kwh': 0.0,
 'out.electricity.clothes_washer.energy_savings..kwh': 0.0,
 'out.electricity.cooling_fans_pumps.energy_savings..kwh': -27.548680598800047,
 'out.electricity.cooling.energy_savings..kwh': -101.40259028920082,
 'out.electricity.dishwasher.energy_savings..kwh': 0.0,
 'out.electricity.ev_charging.energy_savings..kwh': 0.0,
 'out.electricity.freezer.energy_savings..kwh': 0.0,
 'out.electricity.heating_fans_pumps.energy_savings..kwh': -4.1029949827999985,
 'out.electricity.heating_hp_bkup.energy_savings..kwh': 0.0,
 'out.electricity.heating_hp_bkup_fa.energy_savings..kwh': 0.0,
 'out.electricity.heating.energy_savings..kwh': -49.82208193399998,
 'out.electricity.permanent_spa_heat.energy_savings..kwh': 0.0,
 'out.electricity.permanent_spa_pump.energy_savings..kwh': 0.0,
 'out.electricity.hot_water.energy_savings..kwh': -0.2930710701998578,
 'out.electricity.hot_water_solar_th.energy_savings..kwh': 0.0,
 'out.electricity.lighting_exterior.energy_savings..kwh': 0.0,
 'out.electricity.lighting_garage.energy_savings..kwh': 0.0,
 'out.electricity.lighting_interior.energy_savings..kwh': 0.0,
 'out.electricity.mech_vent.energy_savings..kwh': 0.0,

In [189]:
%%time
# extract the climate zone details based on the builings and cast the building id type to match the one in the original data
Meta_data=pl.scan_parquet(meta_data_folder/'MetaData.parquet').with_columns(
    pl.col('bldg_id').cast(pl.UInt32)).filter(
    pl.col('bldg_id').is_in(bldgs
                           )).select(pl.col('in.occupants').cast(pl.Int32),'in.state','in.county',
                        'in.representative_income','in.area_median_income','in.income',
                        'in.income_recs_2020','in.income_recs_2015',
                        'in.building_america_climate_zone','in.ashrae_iecc_climate_zone_2004_sub_cz_split',
                        pl.col('in.bedrooms').cast(pl.Int32),'in.tenure','in.household_has_tribal_persons','bldg_id').unique()

CPU times: user 372 μs, sys: 0 ns, total: 372 μs
Wall time: 383 μs

In [190]:
%%time
# merge the climate zone changes into the original data
df=data.join(Meta_data, on='bldg_id')

CPU times: user 45 μs, sys: 0 ns, total: 45 μs
Wall time: 51 μs

In [191]:
df=df.rename({'in.ashrae_iecc_climate_zone_2004_sub_cz_split': 'climatezone',
                'out.electricity.cooling.energy_consumption..kwh': 'out.electricity.AC.energy_consumption..kwh'}).with_columns(
            pl.col('timestamp').dt.weekday().alias('day of the week'),
            pl.col('timestamp').dt.hour().alias('hour of the day'),
            pl.col('timestamp').dt.day().alias('day of the month'),
            pl.col('timestamp').dt.ordinal_day().alias('day of the year'),
            pl.col('timestamp').dt.week().alias('week of the year'),
            pl.col('timestamp').dt.month().alias('month of the year'),
            pl.col('timestamp').dt.quarter().alias('quarter')).with_columns(
            pl.when(pl.col('day of the week').is_in([6,7])).then(pl.lit("Yes")).otherwise(pl.lit("No")).alias('IsWeekend')
            ).select(
    cs.matches('^out.electricity.*|^out.site_energy.*|^bldg*|^day*|^hour*|^week*|^month*|^time*|^quarter|^IsWeekend|^in.*|^Short|^climatezone$')
).drop_nulls().collect()

In [192]:
# df=df.rename({'in.ashrae_iecc_climate_zone_2004_sub_cz_split': 'climatezone'}).with_columns(
#             pl.col('timestamp').dt.weekday().alias('day of the week'),
#             pl.col('timestamp').dt.hour().alias('hour of the day'),
#             pl.col('timestamp').dt.day().alias('day of the month'),
#             pl.col('timestamp').dt.ordinal_day().alias('day of the year'),
#             pl.col('timestamp').dt.week().alias('week of the year'),
#             pl.col('timestamp').dt.month().alias('month of the year'),
#             pl.col('timestamp').dt.quarter().alias('quarter')).with_columns(
#             pl.when(pl.col('day of the week').is_in([6,7])).then(pl.lit("Yes")).otherwise(pl.lit("No")).alias('is_weekend')
#             ).select(
#     cs.matches('^out.electricity.*|^out.site_energy.*|^bldg*|^day*|^hour*|^week*|^month*|^time|^quarter|^is_weekend|^in*|^climatezone$|^in.bedrooms')
# ).drop_nulls().collect()


----------------------------------------------

### Label Encoder for categorical variables

In [193]:
from sklearn.preprocessing import LabelEncoder
def encoding_categories(x):
    le=LabelEncoder()
    for dtype,col in zip(x.dtypes,x.columns):
        if dtype==pl.String:
            x=x.with_columns(pl.Series(col, le.fit_transform(x[col])))
    return x

## Preprocess the data

In [194]:
# defining x and y
def prepare_observations(d):
    x=d.select(cs.matches('^day*|^hour*|^week*|^month*|^time*|^quarter|^IsWeekend|^in.*|^Short|^climatezone$').exclude('in.sqft'),
            pl.col('out.electricity.total.energy_consumption..kwh').alias('total_usage')).with_columns(pl.col('timestamp').dt.timestamp()).select(pl.all().exclude('timestamp'))
    # x=d.select('climatezone','day of the week','hour of the day','day of the month','day of the year',
    #            'week of the year','month of the year','quarter','is_weekend','in.bedrooms','timestamp').with_columns(pl.col('timestamp').dt.timestamp())
    y=d.select(cs.matches('^out.electricity.*..kwh$').exclude('out.electricity.total.energy_consumption..kwh'))
    # y=d.select('out.electricity.heating.energy_consumption..kwh','out.electricity.cooling.energy_consumption..kwh')
    x=encoding_categories(x)
    return x,y

x,y=prepare_observations(df)
x

shape: (595_680, 22)
┌────────────┬──────────┬───────────┬────────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ in.occupan ┆ in.state ┆ in.county ┆ in.represe ┆ … ┆ month of  ┆ quarter ┆ IsWeekend ┆ total_usa │
│ ts         ┆ ---      ┆ ---       ┆ ntative_in ┆   ┆ the year  ┆ ---     ┆ ---       ┆ ge        │
│ ---        ┆ i64      ┆ i64       ┆ come       ┆   ┆ ---       ┆ i8      ┆ i64       ┆ ---       │
│ i32        ┆          ┆           ┆ ---        ┆   ┆ i8        ┆         ┆           ┆ f32       │
│            ┆          ┆           ┆ f32        ┆   ┆           ┆         ┆           ┆           │
╞════════════╪══════════╪═══════════╪════════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ 4          ┆ 0        ┆ 6         ┆ 32414.0    ┆ … ┆ 1         ┆ 1       ┆ 0         ┆ 0.1662    │
│ 4          ┆ 0        ┆ 6         ┆ 32414.0    ┆ … ┆ 1         ┆ 1       ┆ 0         ┆ 0.15641   │
│ 4          ┆ 0        ┆ 6         ┆ 32414.0    ┆ … ┆ 1         ┆ 1       ┆ 0         ┆ 0.14339   │
│ 4          ┆ 0        ┆ 6         ┆ 32414.0    ┆ … ┆ 1         ┆ 1       ┆ 0         ┆ 0.14249   │
│ 4          ┆ 0        ┆ 6         ┆ 32414.0    ┆ … ┆ 1         ┆ 1       ┆ 0         ┆ 0.14133   │
│ …          ┆ …        ┆ …         ┆ …          ┆ … ┆ …         ┆ …       ┆ …         ┆ …         │
│ 4          ┆ 0        ┆ 5         ┆ 129716.0   ┆ … ┆ 12        ┆ 4       ┆ 0         ┆ 0.47071   │
│ 4          ┆ 0        ┆ 5         ┆ 129716.0   ┆ … ┆ 12        ┆ 4       ┆ 0         ┆ 0.22021   │
│ 4          ┆ 0        ┆ 5         ┆ 129716.0   ┆ … ┆ 12        ┆ 4       ┆ 0         ┆ 0.21864   │
│ 4          ┆ 0        ┆ 5         ┆ 129716.0   ┆ … ┆ 12        ┆ 4       ┆ 0         ┆ 0.23577   │
│ 4          ┆ 0        ┆ 5         ┆ 129716.0   ┆ … ┆ 1         ┆ 1       ┆ 0         ┆ 0.22983   │
└────────────┴──────────┴───────────┴────────────┴───┴───────────┴─────────┴───────────┴───────────┘

## test standardizing the data with the standard scaler

In [195]:
from sklearn.preprocessing import StandardScaler
def normlize_standard(x,y=None):
    scaler=StandardScaler()
    x=scaler.fit_transform(x)
    if y is not None:
        y=scaler.fit_transform(y)
        return x, y
    else:
        return x

## test standardizing the data with the Min Max Scaler

In [196]:
from sklearn.preprocessing import MinMaxScaler
def normalize_minMax(x, y=None):
    scaler=MinMaxScaler()
    x=scaler.fit_transform(x)
    if y is not None:
        y=scaler.fit_transform(y)
        return x,y 
    else:
        return x

### Prepare cross-validation model

In [197]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, root_mean_squared_error
def model(mod, x_train, x_test, y_train, y_test, metric):
    mod.fit(x_train, y_train)
    predicted=mod.predict(x_test)
    return metric(y_test, predicted)
        # r2_score(y_test, predicted)
        # mean_absolute_error(y_test, predicted), 
        # mean_squared_error(y_test, predicted), 
        # root_mean_squared_error(y_test, predicted)

In [198]:
from sklearn.model_selection import train_test_split, StratifiedKFold, KFold, cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.utils import shuffle
import xgboost as xg
def cross_folding(x,y, metric):
    kf=KFold(n_splits=5, shuffle=True)
    arr=[]
    lf=pd.DataFrame()
    for i, (train,test) in enumerate(kf.split(x,y)):
        x_train, x_test, y_train, y_test=x[train], x[test], y[train], y[test]
        LR=model(LinearRegression(), x_train, x_test, y_train, y_test, metric)
        RF=model(RandomForestRegressor(n_estimators=3, max_depth=2, n_jobs=-1), x_train, x_test, y_train, y_test, metric)
        XG=model(xg.XGBRegressor(learning_rate= 0.1, max_depth= 7, subsample= 0.7), x_train, x_test, y_train, y_test, metric)
        frame=pd.DataFrame({
        "Split Number": [i],
        "Linear Regression": [LR],
        "Random Forest": [RF],
        "XG Boost": [XG]
        })
        arr.append(frame)
    lf=pd.concat(arr)
    return lf.mean()

In [199]:
def without_preprocessing(d):
    x,y=prepare_observations(d)
    average=cross_folding(x, y, r2_score)
    return average

In [200]:
def with_standardScalar(d):
    x,y=prepare_observations(d)
    x=normlize_standard(x)
    average=cross_folding(x, y, r2_score)
    return average

In [201]:
def with_minMaxScalar(d):
    x,y=prepare_observations(d)
    x=normalize_minMax(x)
    average=cross_folding(x, y, r2_score)
    return average

In [202]:
def apply_modelling(d):
    average_0=without_preprocessing(d)
    average_1=with_standardScalar(d)
    average_2=with_minMaxScalar(d)   
    return pd.concat([average_0, average_1, average_2], axis=1, keys=['no normalization','standard Scalar','MinMaxScalar'])

In [203]:
apply_modelling(df)

                   no normalization  standard Scalar  MinMaxScalar
Split Number               2.000000         2.000000      2.000000
Linear Regression          0.430795         0.431226      0.432402
Random Forest              0.242231         0.243725      0.243935
XG Boost                   0.820259         0.834247      0.835252

In [18]:
x, y=prepare_observations(df)
len(y.columns)

29

---------------------

### Tuning XGboost Model

In [28]:
from sklearn.model_selection import GridSearchCV
def tunning(training_data, testing_data, model, param):
        x_train, x_test, y_train, y_test=train_test_split(x,y, test_size=0.3)
        grid_search = GridSearchCV(model, param_grid=param, cv=KFold(3), 
                                   scoring='r2',
                                   n_jobs=-1)
        grid_search.fit(x_train, y_train)
        return grid_search.best_params_, grid_search.best_score_

In [49]:
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
params= {
    'max_depth': [3, 5, 7],
    'learning_rate': [0.1, 0.01, 0.001],
    'subsample': [0.5, 0.7, 1]
}
x,y=prepare_observations(df)
best_param, best_score=tunning(x,y, XGBRegressor(), params)

NameError: name 'tunning' is not defined

In [405]:
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.3, random_state=1)
XG=model(XGBRegressor(learning_rate= 0.1, max_depth= 7, subsample= 0.7), x_train, x_test, y_train, y_test, r2_score)
XG

0.917816162109375

### Deep Learning with pytorch

In [19]:
import torch
import torch.nn as nn
import torch.nn.functional as tf

In [20]:
import gc
torch.cuda.empty_cache()
gc.collect()

4315

In [54]:
class Model(nn.Module):
    def __init__(self, features_num=23, h1=7, h2=8, out_features=29):
        super().__init__()
        self.fc1 = nn.Linear(features_num, h1)
        self.fc2 = nn.Linear(h1, h2)
        self.fc3 = nn.Linear(h2, out_features)
    def forward(self, x):
        x=tf.relu(self.fc1(x))
        x=tf.relu(self.fc2(x))
        x=self.fc3(x)
        return x

In [55]:
from sklearn.model_selection import train_test_split
model=Model()
x,y=prepare_observations(df)
x,y=normlize_standard(x, y)
x_train, x_test, y_train, y_test=train_test_split(x, y, random_state=42, test_size=0.3)
x_train=torch.from_numpy(x_train).float()
x_test=torch.from_numpy(x_test).float()
y_train=torch.from_numpy(y_train).float()
y_test=torch.from_numpy(y_test).float()

In [56]:
## Creating a criterion to measure the error of the model
criterion=nn.MSELoss()

In [57]:
optimizer=torch.optim.Adam(model.parameters(),lr=0.01)

In [58]:
# from torch.utils.data import TensorDataset, DataLoader
# data_set=TensorDataset(x_train, y_train)
# dataset=DataLoader(dataset=data_set, batch_size=2048, shuffle=True)

In [ ]:
epochs=10000
losses=[]
for i in range(epochs):
    # for x, y in dataset:
    y_pred=model.forward(x_train)
    loss=criterion(y_pred, y_train)
    losses.append(loss)
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()
    if i %10 ==0:
        print(f"{i} iteration, loss: {loss}")

## Calculating measures

In [ ]:
# prepare measurement
Test_data=x.head(1)
Actual_data=y.row(1)

In [52]:
Test_data

NameError: name 'Test_data' is not defined

In [ ]:
Actual_data

In [ ]:
# Select the best model 
import xgboost as xg
from sklearn.model_selection import train_test_split
x,x_test, y, y_test= train_test_split(x,y, test_size=.3, random_state=42)
xg_model=xg.XGBRegressor()
xg_model.fit(x,y)
estimated_values=xg_model.predict(Test_data)

In [ ]:
estimated_values.flatten()

## Observation

Apparently using r square as a metric to represent to the data is a misrepresentation to the model's performance.
R square formula is - >1- ( total of squared residulas /total of squared standard deviation)
Knowing MAE is the total of residuals -> total(y - yPredicted)
giving r square = 0.02 therefore
giving standard deviation of .001 as given above
then r square= .0004 / .00001= 40 -> 1-40 =-39 which is wrong

Therefore, MAE score is the perfect representation of the data.
another testing metric should be provided.

Input data = timestamp Total      Usage     Climate Zone.
             1545212700000000     1.22827       1

Actual result=(0.1280200034379959, 0.0, 0.0, 0.01245999988168478, 0.0).


Estimated result= [2.9516332e-02, 4.0768548e-03, 1.0928856e-17, 1.0773698e-02,
       2.7552096e-03].