### TODO:
1. Load multiple dataset for different buildings.
2. Get the climate info for the state.
3. preprocess the data.
4. Create a linear regression model.
5. Prepare some tests for the model.

In [2]:
import polars as pl
import pyarrow
import pandas as pd
import numpy as np

In [3]:
from pathlib import Path
folder= Path().resolve().parent /'input'

### 1. Load multiple dataset for different buildings.

In [4]:
# read the original data for three individual buildings
data=pl.scan_parquet(folder / 'load_profile_buildingID_*')

In [5]:
# extract the buildings Ids
bldgs=data.select(pl.col('bldg_id').unique()).collect().to_series().to_list()

### 2. Get the climate info for the state.

In [6]:
# extract the climate zone details based on the builings and cast the building id type to match the one in the original data
meta_data=(
    pl.scan_parquet(folder / 'MetaData.parquet')
)            
MetaData=meta_data.filter(
            pl.col('bldg_id').is_in(bldgs)).cast({"bldg_id": pl.UInt32}).select(
            pl.col('bldg_id', 'in.ashrae_iecc_climate_zone_2004_sub_cz_split'))

# MetaData.row(0, named=True) 
MetaData.collect()

shape: (3, 2)
┌─────────┬─────────────────────────────────┐
│ bldg_id ┆ in.ashrae_iecc_climate_zone_20… │
│ ---     ┆ ---                             │
│ u32     ┆ str                             │
╞═════════╪═════════════════════════════════╡
│ 10      ┆ 1A - FL                         │
│ 100016  ┆ 2A - FL, GA, AL, MS             │
│ 100024  ┆ 1A - FL                         │
└─────────┴─────────────────────────────────┘

In [7]:
%%time
# merge the climate zone changes into the original data
df=data.join(MetaData, on='bldg_id')
df.collect_schema()

CPU times: user 2.5 ms, sys: 410 μs, total: 2.91 ms
Wall time: 1.82 ms

Schema([('bldg_id', UInt32),
        ('timestamp', Datetime(time_unit='ms', time_zone=None)),
        ('in.sqft', Float32),
        ('out.electricity.ceiling_fan.energy_consumption..kwh', Float32),
        ('out.electricity.clothes_dryer.energy_consumption..kwh', Float32),
        ('out.electricity.clothes_washer.energy_consumption..kwh', Float32),
        ('out.electricity.cooling.energy_consumption..kwh', Float32),
        ('out.electricity.cooling_fans_pumps.energy_consumption..kwh',
         Float32),
        ('out.electricity.dishwasher.energy_consumption..kwh', Float32),
        ('out.electricity.ev_charging.energy_consumption..kwh', Float32),
        ('out.electricity.freezer.energy_consumption..kwh', Float32),
        ('out.electricity.heating.energy_consumption..kwh', Float32),
        ('out.electricity.heating_fans_pumps.energy_consumption..kwh',
         Float32),
        ('out.electricity.heating_hp_bkup.energy_consumption..kwh', Float32),
        ('out.electricity.heating_hp_bkup_fa.energy_consumption..kwh',
         Float32),
        ('out.electricity.hot_water.energy_consumption..kwh', Float32),
        ('out.electricity.hot_water_solar_th.energy_consumption..kwh',
         Float32),
        ('out.electricity.lighting_exterior.energy_consumption..kwh', Float32),
        ('out.electricity.lighting_garage.energy_consumption..kwh', Float32),
        ('out.electricity.lighting_interior.energy_consumption..kwh', Float32),
        ('out.electricity.mech_vent.energy_consumption..kwh', Float32),
        ('out.electricity.net.energy_consumption..kwh', Float32),
        ('out.electricity.permanent_spa_heat.energy_consumption..kwh',
         Float32),
        ('out.electricity.permanent_spa_pump.energy_consumption..kwh',
         Float32),
        ('out.electricity.plug_loads.energy_consumption..kwh', Float32),
        ('out.electricity.pool_heater.energy_consumption..kwh', Float32),
        ('out.electricity.pool_pump.energy_consumption..kwh', Float32),
        ('out.electricity.pv.energy_consumption..kwh', Float32),
        ('out.electricity.range_oven.energy_consumption..kwh', Float32),
        ('out.electricity.refrigerator.energy_consumption..kwh', Float32),
        ('out.electricity.television.energy_consumption..kwh', Float32),
        ('out.electricity.total.energy_consumption..kwh', Float32),
        ('out.electricity.well_pump.energy_consumption..kwh', Float32),
        ('out.fuel_oil.heating.energy_consumption..kwh', Float32),
        ('out.fuel_oil.hot_water.energy_consumption..kwh', Float32),
        ('out.fuel_oil.total.energy_consumption..kwh', Float32),
        ('out.natural_gas.clothes_dryer.energy_consumption..kwh', Float32),
        ('out.natural_gas.fireplace.energy_consumption..kwh', Float32),
        ('out.natural_gas.grill.energy_consumption..kwh', Float32),
        ('out.natural_gas.heating.energy_consumption..kwh', Float32),
        ('out.natural_gas.heating_hp_bkup.energy_consumption..kwh', Float32),
        ('out.natural_gas.hot_water.energy_consumption..kwh', Float32),
        ('out.natural_gas.lighting.energy_consumption..kwh', Float32),
        ('out.natural_gas.permanent_spa_heat.energy_consumption..kwh',
         Float32),
        ('out.natural_gas.pool_heater.energy_consumption..kwh', Float32),
        ('out.natural_gas.range_oven.energy_consumption..kwh', Float32),
        ('out.natural_gas.total.energy_consumption..kwh', Float32),
        ('out.propane.clothes_dryer.energy_consumption..kwh', Float32),
        ('out.propane.heating.energy_consumption..kwh', Float32),
        ('out.propane.hot_water.energy_consumption..kwh', Float32),
        ('out.propane.range_oven.energy_consumption..kwh', Float32),
        ('out.propane.total.energy_consumption..kwh', Float32),
        ('out.site_energy.net.energy_consumption..kwh', Float32),
        ('out.site_energy.total.energy_consumption..kwh', Float32),
        ('out.electricity.ceiling_fan.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.electricity.clothes_dryer.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.electricity.clothes_washer.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.electricity.cooling.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.electricity.cooling_fans_pumps.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.electricity.dishwasher.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.electricity.ev_charging.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.electricity.freezer.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.electricity.heating.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.electricity.heating_fans_pumps.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.electricity.heating_hp_bkup.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.electricity.heating_hp_bkup_fa.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.electricity.hot_water.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.electricity.hot_water_solar_th.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.electricity.lighting_exterior.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.electricity.lighting_garage.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.electricity.lighting_interior.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.electricity.mech_vent.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.electricity.net.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.electricity.permanent_spa_heat.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.electricity.permanent_spa_pump.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.electricity.plug_loads.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.electricity.pool_heater.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.electricity.pool_pump.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.electricity.pv.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.electricity.range_oven.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.electricity.refrigerator.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.electricity.television.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.electricity.total.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.electricity.well_pump.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.fuel_oil.heating.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.fuel_oil.hot_water.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.fuel_oil.total.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.natural_gas.clothes_dryer.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.natural_gas.fireplace.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.natural_gas.grill.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.natural_gas.heating.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.natural_gas.heating_hp_bkup.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.natural_gas.hot_water.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.natural_gas.lighting.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.natural_gas.permanent_spa_heat.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.natural_gas.pool_heater.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.natural_gas.range_oven.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.natural_gas.total.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.propane.clothes_dryer.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.propane.heating.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.propane.hot_water.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.propane.range_oven.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.propane.total.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.site_energy.net.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.site_energy.total.energy_consumption_intensity..kwh_per_ft2',
         Float32),
        ('out.emissions.electricity.total.aer_highrecost_avg..co2e_kg',
         Float32),
        ('out.emissions.electricity.total.aer_highrecostlowngprice_avg..co2e_kg',
         Float32),
        ('out.emissions.electricity.total.aer_lowrecost_avg..co2e_kg',
         Float32),
        ('out.emissions.electricity.total.aer_lowrecosthighngprice_avg..co2e_kg',
         Float32),
        ('out.emissions.electricity.total.aer_midcase_avg..co2e_kg', Float32),
        ('out.emissions.electricity.total.lrmer_highrecost_15..co2e_kg',
         Float32),
        ('out.emissions.electricity.total.lrmer_highrecost_25..co2e_kg',
         Float32),
        ('out.emissions.electricity.total.lrmer_highrecostlowngprice_15..co2e_kg',
         Float32),
        ('out.emissions.electricity.total.lrmer_highrecostlowngprice_25..co2e_kg',
         Float32),
        ('out.emissions.electricity.total.lrmer_lowrecost_15..co2e_kg',
         Float32),
        ('out.emissions.electricity.total.lrmer_lowrecost_25..co2e_kg',
         Float32),
        ('out.emissions.electricity.total.lrmer_lowrecosthighngprice_15..co2e_kg',
         Float32),
        ('out.emissions.electricity.total.lrmer_lowrecosthighngprice_25..co2e_kg',
         Float32),
        ('out.emissions.electricity.total.lrmer_midcase_15..co2e_kg', Float32),
        ('out.emissions.electricity.total.lrmer_midcase_25..co2e_kg', Float32),
        ('out.emissions.natural_gas.total..co2e_kg', Float32),
        ('out.emissions.propane.total..co2e_kg', Float32),
        ('out.emissions.fuel_oil.total..co2e_kg', Float32),
        ('out.emissions.total.aer_highrecost_avg..co2e_kg', Float32),
        ('out.emissions.total.aer_highrecostlowngprice_avg..co2e_kg', Float32),
        ('out.emissions.total.aer_lowrecost_avg..co2e_kg', Float32),
        ('out.emissions.total.aer_lowrecosthighngprice_avg..co2e_kg', Float32),
        ('out.emissions.total.aer_midcase_avg..co2e_kg', Float32),
        ('out.emissions.total.lrmer_highrecost_15..co2e_kg', Float32),
        ('out.emissions.total.lrmer_highrecost_25..co2e_kg', Float32),
        ('out.emissions.total.lrmer_highrecostlowngprice_15..co2e_kg',
         Float32),
        ('out.emissions.total.lrmer_highrecostlowngprice_25..co2e_kg',
         Float32),
        ('out.emissions.total.lrmer_lowrecost_15..co2e_kg', Float32),
        ('out.emissions.total.lrmer_lowrecost_25..co2e_kg', Float32),
        ('out.emissions.total.lrmer_lowrecosthighngprice_15..co2e_kg',
         Float32),
        ('out.emissions.total.lrmer_lowrecosthighngprice_25..co2e_kg',
         Float32),
        ('out.emissions.total.lrmer_midcase_15..co2e_kg', Float32),
        ('out.emissions.total.lrmer_midcase_25..co2e_kg', Float32),
        ('out.unmet_hours.cooling..hour', Float32),
        ('out.unmet_hours.ev_driving..hour', Float32),
        ('out.unmet_hours.heating..hour', Float32),
        ('out.hot_water.clothes_washer..gal', Float32),
        ('out.hot_water.dishwasher..gal', Float32),
        ('out.hot_water.distribution_waste..gal', Float32),
        ('out.hot_water.fixtures..gal', Float32),
        ('out.load.cooling.energy_delivered..kbtu', Float32),
        ('out.load.heating.energy_delivered..kbtu', Float32),
        ('out.load.heating_heat_pump_backup..kbtu', Float32),
        ('out.load.hot_water.energy_delivered..kbtu', Float32),
        ('out.load.hot_water_solar_thermal..kbtu', Float32),
        ('out.load.hot_water_tank_losses..kbtu', Float32),
        ('out.indoor_airflow.infiltration..cfm', Float32),
        ('out.indoor_airflow.mechanical_ventilation..cfm', Float32),
        ('out.indoor_airflow.natural_ventilation..cfm', Float32),
        ('out.indoor_dewpoint_temperature.conditioned_space..c', Float32),
        ('out.indoor_humidity_ratio.conditioned_space..kgwater_per_kgdryair',
         Float32),
        ('out.indoor_operative_temperature.conditioned_space..c', Float32),
        ('out.indoor_radiant_temperature.conditioned_space..c', Float32),
        ('out.indoor_relative_humidity.conditioned_space..percentage',
         Float32),
        ('out.indoor_temperature.conditioned_space..c', Float32),
        ('out.outdoor_air_drybulb_temp..c', Float32),
        ('out.outdoor_air_relative_humidity..percentage', Float32),
        ('out.outdoor_air_wetbulb_temp..c', Float32),
        ('out.outdoor_humidity_ratio..kgwater_per_kgdryair', Float32),
        ('out.people.sensible_heating_rate..watt', Float32),
        ('out.people.total_heating_rate..watt', Float32),
        ('out.weather.diffuse_solar_radiation..watt_per_m2', Float32),
        ('out.weather.direct_normal_solar_radiation..watt_per_m2', Float32),
        ('out.weather.wind_speed..meter_per_second', Float32),
        ('out.schedules.ceiling_fan', Float32),
        ('out.schedules.clothes_dryer', Float32),
        ('out.schedules.clothes_washer', Float32),
        ('out.schedules.cooking_range', Float32),
        ('out.schedules.cooling_setpoint..c', Float32),
        ('out.schedules.dishwasher', Float32),
        ('out.schedules.electric_vehicle_charging', Float32),
        ('out.schedules.electric_vehicle_discharging', Float32),
        ('out.schedules.heating_setpoint..c', Float32),
        ('out.schedules.hot_water_clothes_washer', Float32),
        ('out.schedules.hot_water_dishwasher', Float32),
        ('out.schedules.hot_water_fixtures', Float32),
        ('out.schedules.lighting_garage', Float32),
        ('out.schedules.lighting_interior', Float32),
        ('out.schedules.no_space_cooling', Float32),
        ('out.schedules.no_space_heating', Float32),
        ('out.schedules.occupants', Float32),
        ('out.schedules.peak_period', Float32),
        ('out.schedules.plug_loads_other', Float32),
        ('out.schedules.plug_loads_tv', Float32),
        ('out.schedules.power_outage', Float32),
        ('out.schedules.pre_peak_period', Float32),
        ('out.schedules.vacancy', Float32),
        ('in.ashrae_iecc_climate_zone_2004_sub_cz_split', String)])

There are only time two climate zones for the data

----------------------------------------------

## Explore the data to get insights

In [8]:
import polars.selectors as pls
df=df.select(pls.matches(r'bldg_id|timestamp|in.ashrae_iecc_climate_zone_*|out.electricity.*?.energy_consumption..kwh'))

In [9]:
meta_data.collect()

shape: (549_971, 620)
┌─────────┬─────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ bldg_id ┆ upgrade ┆ upgrade_na ┆ weight     ┆ … ┆ out.bills. ┆ out.energ ┆ upgrade.d ┆ upgrade.d │
│ ---     ┆ ---     ┆ me         ┆ ---        ┆   ┆ all_fuels. ┆ y_burden. ┆ emand_fle ┆ emand_fle │
│ i64     ┆ i32     ┆ ---        ┆ f64        ┆   ┆ usd.saving ┆ percentag ┆ xibility_ ┆ xibility_ │
│         ┆         ┆ str        ┆            ┆   ┆ …          ┆ e.s…      ┆ hva…      ┆ ran…      │
│         ┆         ┆            ┆            ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│         ┆         ┆            ┆            ┆   ┆ f64        ┆ f64       ┆ str       ┆ str       │
╞═════════╪═════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 1       ┆ 28      ┆ HVAC       ┆ 253.903673 ┆ … ┆ -4.44      ┆ 0.0       ┆ Pre-peak  ┆ 30        │
│         ┆         ┆ Demand Fle ┆            ┆   ┆            ┆           ┆ Load      ┆ minutes   │
│         ┆         ┆ xibility - ┆            ┆   ┆            ┆           ┆ Shifting, ┆           │
│         ┆         ┆ Pre-…      ┆            ┆   ┆            ┆           ┆ 2F Off…   ┆           │
│ 2       ┆ 28      ┆ HVAC       ┆ 253.903673 ┆ … ┆ -19.59     ┆ 0.0       ┆ Pre-peak  ┆ 30        │
│         ┆         ┆ Demand Fle ┆            ┆   ┆            ┆           ┆ Load      ┆ minutes   │
│         ┆         ┆ xibility - ┆            ┆   ┆            ┆           ┆ Shifting, ┆           │
│         ┆         ┆ Pre-…      ┆            ┆   ┆            ┆           ┆ 2F Off…   ┆           │
│ 3       ┆ 28      ┆ HVAC       ┆ 253.903673 ┆ … ┆ -18.95     ┆ 0.0       ┆ Pre-peak  ┆ 30        │
│         ┆         ┆ Demand Fle ┆            ┆   ┆            ┆           ┆ Load      ┆ minutes   │
│         ┆         ┆ xibility - ┆            ┆   ┆            ┆           ┆ Shifting, ┆           │
│         ┆         ┆ Pre-…      ┆            ┆   ┆            ┆           ┆ 2F Off…   ┆           │
│ 4       ┆ 28      ┆ HVAC       ┆ 253.903673 ┆ … ┆ -2.56      ┆ 0.0       ┆ Pre-peak  ┆ 30        │
│         ┆         ┆ Demand Fle ┆            ┆   ┆            ┆           ┆ Load      ┆ minutes   │
│         ┆         ┆ xibility - ┆            ┆   ┆            ┆           ┆ Shifting, ┆           │
│         ┆         ┆ Pre-…      ┆            ┆   ┆            ┆           ┆ 2F Off…   ┆           │
│ 5       ┆ 28      ┆ HVAC       ┆ 253.903673 ┆ … ┆ -0.29      ┆ 0.0       ┆ Pre-peak  ┆ 30        │
│         ┆         ┆ Demand Fle ┆            ┆   ┆            ┆           ┆ Load      ┆ minutes   │
│         ┆         ┆ xibility - ┆            ┆   ┆            ┆           ┆ Shifting, ┆           │
│         ┆         ┆ Pre-…      ┆            ┆   ┆            ┆           ┆ 2F Off…   ┆           │
│ …       ┆ …       ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 549996  ┆ 28      ┆ HVAC       ┆ 253.903673 ┆ … ┆ -20.9      ┆ 0.0       ┆ Pre-peak  ┆ 30        │
│         ┆         ┆ Demand Fle ┆            ┆   ┆            ┆           ┆ Load      ┆ minutes   │
│         ┆         ┆ xibility - ┆            ┆   ┆            ┆           ┆ Shifting, ┆           │
│         ┆         ┆ Pre-…      ┆            ┆   ┆            ┆           ┆ 2F Off…   ┆           │
│ 549997  ┆ 28      ┆ HVAC       ┆ 253.903673 ┆ … ┆ -2.03      ┆ 0.0       ┆ Pre-peak  ┆ 30        │
│         ┆         ┆ Demand Fle ┆            ┆   ┆            ┆           ┆ Load      ┆ minutes   │
│         ┆         ┆ xibility - ┆            ┆   ┆            ┆           ┆ Shifting, ┆           │
│         ┆         ┆ Pre-…      ┆            ┆   ┆            ┆           ┆ 2F Off…   ┆           │
│ 549998  ┆ 28      ┆ HVAC       ┆ 253.903673 ┆ … ┆ -21.64     ┆ 0.0       ┆ Pre-peak  ┆ 30        │
│         ┆         ┆ Demand Fle ┆            ┆   ┆            ┆           ┆ Load      ┆ minutes   │
│         ┆         ┆ xibility - ┆            ┆   ┆            ┆           ┆ Shifting, ┆           │
│         ┆         ┆ Pre-…      ┆            ┆   ┆            ┆           ┆ 2F Off…   ┆           │
│ 549999  ┆ 28      ┆ HVAC       ┆ 253.903673 ┆ … ┆ -0.01      ┆ 0.0       ┆ Pre-peak  ┆ 30        │
│         ┆         ┆ Demand Fle ┆            ┆   ┆            ┆           ┆ Load      ┆ minutes   │
│         ┆         ┆ xibility - ┆            ┆   ┆            ┆           ┆ Shifting, ┆           │
│         ┆         ┆ Pre-…      ┆            ┆   ┆            ┆           ┆ 2F Off…   ┆           │
│ 550000  ┆ 28      ┆ HVAC       ┆ 253.903673 ┆ … ┆ -61.6      ┆ 0.0       ┆ Pre-peak  ┆ 30        │
│         ┆         ┆ Demand Fle ┆            ┆   ┆            ┆           ┆ Load      ┆ minutes   │
│         ┆         ┆ xibility - ┆            ┆   ┆            ┆           ┆ Shifting, ┆           │
│         ┆         ┆ Pre-…      ┆            ┆   ┆            ┆           ┆ 2F Off…   ┆           │
└─────────┴─────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

## Preprocess the data

In [11]:
# defining the independant and dependant variables with encoding categorical variables and converting the datetime to a timestamp
x= df.select(pl.col("timestamp").dt.timestamp(), pl.col('out.electricity.total.energy_consumption..kwh').alias('Total Usage'),
             pl.col('in.ashrae_iecc_climate_zone_2004_sub_cz_split').cast(pl.Categorical).cast(pl.UInt32).alias('Climate Zone')).collect()
y=df.select(pl.col("out.electricity.cooling.energy_consumption..kwh").alias('Cooling Consumption'),
           pl.col("out.electricity.heating.energy_consumption..kwh").alias('Heating Consumption'),
           pl.col("out.electricity.freezer.energy_consumption..kwh").alias('Freezing Consumption'),
           pl.col("out.electricity.refrigerator.energy_consumption..kwh").alias('Refrigerator Consumption'),
           pl.col("out.electricity.dishwasher.energy_consumption..kwh").alias('Dishwasher Consumption')).collect()

## test standardizing the data with the standard scaler

In [ ]:
# from sklearn.preprocessing import StandardScaler
# scaler=StandardScaler()
# x=scaler.fit_transform(x)

## test standardizing the data with the Min Max Scaler

In [ ]:
# from sklearn.preprocessing import MinMaxScaler
# scaler=MinMaxScaler()
# x=scaler.fit_transform(x)

### Prepare cross-validation model

In [39]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, root_mean_squared_error
def model(mod, x_train, x_test, y_train, y_test):
    mod.fit(x_train, y_train)
    predicted=mod.predict(x_test)
    print(np.var(predicted))
    return mean_absolute_error(y_test, predicted)
        # r2_score(y_test, predicted)
        # mean_absolute_error(y_test, predicted), 
        # mean_squared_error(y_test, predicted), 
        # root_mean_squared_error(y_test, predicted)

In [40]:
%%time
from sklearn.model_selection import train_test_split, StratifiedKFold, KFold, cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
import xgboost as xg
skf= StratifiedKFold(n_splits=6)
kf=KFold(n_splits=10)
arr=[]
lf=pd.DataFrame()
for i, (train,test) in enumerate(kf.split(x,y)):
    x_train, x_test, y_train, y_test=x[train], x[test], y[train], y[test]
    LR=model(LinearRegression(), x_train, x_test, y_train, y_test)
    RF=model(RandomForestRegressor(n_estimators=3, max_depth=2, n_jobs=-1), x_train, x_test, y_train, y_test)
    XG=model(xg.XGBRegressor(), x_train, x_test, y_train, y_test)
    frame=pd.DataFrame({
    "Split Number": [i],
    "Linear Regression": [LR],
    "Random Forest": [RF],
    "XG Boost": [XG]
    })
    arr.append(frame)
lf=pd.concat(arr)

0.0018806597185544076
0.0011532428446227882
0.0010672022
0.0025893999072238182
0.004382588960259274
0.0021890434
0.004176325456547316
0.004896907258599078
0.002053468
0.0032644168535019033
0.006427220604040387
0.001611795
0.0019773456900077924
0.0049310795632493505
0.010738795
0.0025430926963733815
0.007190463698015772
0.02016055
0.004376109143620195
0.006409916506143038
0.0078929765
0.0023978636848175547
0.00196787716437077
0.001914812
0.0035704713701757975
0.0028737772779403995
0.0037898668
0.007329796457041308
0.0032790681620729362
0.002687787
CPU times: user 1min 52s, sys: 562 ms, total: 1min 53s
Wall time: 9.54 s

## Calculating measures

In [41]:
lf.mean()

Split Number         4.500000
Linear Regression    0.028079
Random Forest        0.022199
XG Boost             0.019776
dtype: float64

In [64]:
# prepare measurement
Test_data=x.head(1)
Actual_data=y.row(1)

In [66]:
Test_data

shape: (1, 3)
┌──────────────────┬─────────────┬──────────────┐
│ timestamp        ┆ Total Usage ┆ Climate Zone │
│ ---              ┆ ---         ┆ ---          │
│ i64              ┆ f32         ┆ u32          │
╞══════════════════╪═════════════╪══════════════╡
│ 1545212700000000 ┆ 1.22827     ┆ 1            │
└──────────────────┴─────────────┴──────────────┘

In [64]:
Actual_data

(0.1280200034379959, 0.0, 0.0, 0.01245999988168478, 0.0)

In [65]:
# Select the best model 
import xgboost as xg
from sklearn.model_selection import train_test_split
x,x_test, y, y_test= train_test_split(x,y, test_size=.3, random_state=42)
xg_model=xg.XGBRegressor()
xg_model.fit(x,y)
estimated_values=xg_model.predict(Test_data)

In [68]:
estimated_values.flatten()

array([2.9516332e-02, 4.0768548e-03, 1.0928856e-17, 1.0773698e-02,
       2.7552096e-03], dtype=float32)

## Observation

Apparently using r square as a metric to represent to the data is a misrepresentation to the model's performance.
R square formula is - >1- ( total of squared residulas /total of squared standard deviation)
Knowing MAE is the total of residuals -> total(y - yPredicted)
giving r square = 0.02 therefore
giving standard deviation of .001 as given above
then r square= .0004 / .00001= 40 -> 1-40 =-39 which is wrong

Therefore, MAE score is the perfect representation of the data.
another testing metric should be provided.

Input data = timestamp Total      Usage     Climate Zone.
             1545212700000000     1.22827       1

Actual result=(0.1280200034379959, 0.0, 0.0, 0.01245999988168478, 0.0).


Estimated result= [2.9516332e-02, 4.0768548e-03, 1.0928856e-17, 1.0773698e-02,
       2.7552096e-03].